export const carModel = {
  name: '',
  price: 0,
  capacity: 0,
  engine: '',
  image: '',
  poster: '',
  number_of_seats: 0,
  hover_image: '',
  gearbox: '',
  specification: {
    origin: '',
    fuel: '',
    emissions: '',
    dimensions: '',
    base_length: 0,
    base_front_width: 0,
    base_back_width: 0,
    light_undercarriage: 0,
    minimum_rev_radius: 0,
    weight: 0,
    weight_load: 0,
    fuel_capacity: 0,
    luggage_capacity: 0,
    urban_fuel_consumption: 0,
    fuel_consumption: 0,
    combine_fuel_consumption: 0,
    engine_type: '',
    number_of_xylanh: 0,
    xylanh_layout: '',
    xylanh_capacity: 0,
    fuel_system: '',
    fuel_category: '',
    power: '',
    momen: '',
    driver_type: '',
    front_hang_system: '',
    back_hang_system: '',
    drive_system: '',
    rim: '',
    tire_size: '',
    tire_backup: '',
    front_brake: '',
    back_brake: '',
    near_lamp: '',
    far_lamp: '',
    remind_light_system: '',
    fog_light: '',
  },
  carCategory: {
    name: '',
  },
  carModel: {
    name: '',
  },
  promotion: {
    promotionDetails: '',
    discountPercentage: 0,
    startDate: '',
    endDate: '',
  },
  inventory: {
    quantity: 0,
  },
};
