export const carModel = {
  name: '',
  price: '',
  capacity: '',
  engine: '',
  image: '',
  poster: '',
  number_of_seats: '',
  hover_image: '',
  gearbox: '',
  specification: {
    origin: '',
    fuel: '',
    emissions: '',
    dimensions: '',
    base_length: '',
    base_front_width: '',
    base_back_width: '',
    light_undercarriage: '',
    minimum_rev_radius: '',
    weight: '',
    weight_load: '',
    fuel_capacity: '',
    luggage_capacity: '',
    urban_fuel_consumption: '',
    fuel_consumption: '',
    combine_fuel_consumption: '',
    engine_type: '',
    number_of_xylanh: '',
    xylanh_layout: '',
    xylanh_capacity: '',
    fuel_system: '',
    fuel_category: '',
    power: '',
    momen: '',
    driver_type: '',
    front_hang_system: '',
    back_hang_system: '',
    drive_system: '',
    rim: '',
    tire_size: '',
    tire_backup: '',
    front_brake: '',
    back_brake: '',
    near_lamp: '',
    far_lamp: '',
    remind_light_system: '',
    fog_light: '',
  },
  carCategory: {
    name: '',
  },
  carModel: {
    name: '',
  },
  promotion: {
    promotionDetails: '',
    discountPercentage: '',
    startDate: '',
    endDate: '',
  },
  inventory: {
    quantity: '',
  },
};
